### ISSUE TITLE
Add error details on PrComet::Errors::ExistUncommittedModify

### ISSUE THREAD

**Issue by ryz310** [ryz310/pr_comet#279]
It have to show `$ git status` result.
I was wondering what the problem:
![image](https://user-images.githubusercontent.com/3985540/125538970-29e06479-d5c2-4ae0-9412-0241df7a2ad3.png)

**Comment by mathieujobin** [comment]
is this what you mean ? https://github.com/mathieujobin/pr_comet/pull/1

**Comment by ryz310** [comment]
Fixed by #321
